# @package _global_

defaults:
  - model: loger.yaml
  - train: train_loger_first_stage
  - data: scannet.yaml
  - general: default.yaml
  - extras: default.yaml
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog
  - _self_
