# @package _global_

trainer: trainers.loger_trainer.LoGeRTrainer

train:
  sequence_length: 128
  max_img_per_gpu: 128
  window_size_range: [4, 12]
  overlap_size_range: [1, 3]
  iters_per_epoch: 1500

  # low resolution
  resolution: 
    - [504, 280]

model:
  ckpt: ckpts/LoGeR/latest.pt