# @package _global_

trainer: trainers.loger_trainer.Pi3Trainer

train:
  sequence_length: 48
  max_img_per_gpu: 144
  chunk_size_range: [12, 12]
  overlap_size_range: [3, 3]
  iters_per_epoch: 10000

  # low resolution
  resolution: 
    - [504, 280]

model:
  ckpt: ckpts/LoGeR/latest.pt